---
title: "Naissance"
author: "Eagle IO"
date: "1/14/2021"
output: pdf_document
---

```{r,echo=FALSE,include=FALSE}
library(readxl)
library(tidyverse)
library(stringr)
library(psych)
library(caret)
library(ggplot2)
library(car)
library(ggthemes)
library(plyr)
library(scales)
library(zoo)
library(descr)
library(dplyr)
library(tidymodels)
library(class)
library(kknn)
library(janitor)
library(CGPfunctions)
library(summarytools)
library(ggpubr)
library(stringi)
library(hrbrthemes)
library(tidyr)
library(viridis)
library(e1071)
library(moments)
library(rstatix)
library(rpart)
library(rpart.plot)
library(randomForest)
library(caTools)

# Remember to change the location to your computer or flashdrive. 
data <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/ColumbiaThreadNeedle.csv",na.strings="")

data2 <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/Hartford-Funds.csv",na.strings="")

data3 <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/William Blair.csv",na.strings="")

data4 <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/PGIM Metrics.csv",na.strings="")

data5 <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/Asset Manager Level Data.csv",na.strings="")

data6 <-read.csv(file="E:/Montclair State University/EagleIO/Naissance/Data/Asset Manager Product Data.csv",na.strings="")

```

```{r}
data2<-data2%>%select(Asset.Manager.Short.Name:unsubscribe_rate)

data<-data%>%dplyr::rename(Manager.Name=Asset.Manager.Short.Name,
                           Date=Date.and.time.sent,
                           Reference.Name=Email.Name,
                           Opened=X..opened,
                           Clicked=X..clicked,
                           Bounced=X..bounced,
                           Unsubscribed=X..unsubscribed)

data2<-data2%>%dplyr::rename(Manager.Name=Asset.Manager.Short.Name,
                             Date=send.time,
                             Reference.Name=reference_name,
                             From=from,
                             Mail.Type=mail_type,
                             Product.Name=product_name,
                             Subscription=subscription,
                             Audience.Size=audience_size,
                             Blast.Message=blast_message,
                             Distribution.Partner.Specific=distribution_partner_specific,
                             Preferred.Partner=preferred_partner,
                             Producers.Only=producers_only,
                             Prospects.Only=prospects_only,
                             Opened=open_rate,
                             Clicked=clickthrough_rate,
                             Bounced=bounce_rate,
                             Unsubscribed=unsubscribe_rate)

data3<-data3%>%dplyr::rename(Manager.Name=Asset.Manager.Short.Name,
                             Date=Send.Time,
                             Reference.Name=Reference.Name,
                             From=From,
                             Mail.Type=Mail.Type,
                             Product.Name=Product.Name,
                             Subscription=Subscription,
                             Audience.Size=Audience.Size,
                             Blast.Message=Blast.Message,
                             Distribution.Partner.Specific=Distribution.Partner.Specific,
                             Preferred.Partner=Preferred.Partner,
                             Producers.Only=Producers.Only,
                             Prospects.Only=Prospects.Only,
                             Opened=Open.Rate,
                             Clicked=Clickthrough.Rate,
                             Bounced=Bounce.Rate,
                             Unsubscribed=Unsubscribe.Rate)

data4<-data4%>%dplyr::rename(Manager.Name=Asset.Manager.Short.Name,
                             Date=SendStartTime,
                             Reference.Name=EmailName,
                             From=From,
                             Mail.Type=Mail.Type,
                             Product.Name=Product.Name,
                             Subscription=Subscription,
                             Audience.Size=Audience.Size,
                             Blast.Message=Blast.Message,
                             Distribution.Partner.Specific=Distribution.Partner.Specific,
                             Preferred.Partner=Preferred.Partner,
                             Producers.Only=Producers.Only,
                             Prospects.Only=Prospects.Only,
                             Opened=OpenRate,
                             Clicked=ClickRate,
                             Bounced=OverallBounceRate,
                             Unsubscribed=UnsubscribeRate)

                     
```


```{r, include=FALSE}
# Data 1
#Cleaning up
Data_Time<-strsplit(data$Date,split = " ")
result <-  do.call(rbind, Data_Time)
Date<-as.data.frame(result[,1])
Time<-as.data.frame(result[,2])

#Rename Days and Time

Date<-Date%>%dplyr::rename(date=`result[, 1]`)
Time<-Time%>%dplyr::rename(time=`result[, 2]`)

Date$date<-gsub("2021","2020",Date$date)

Date$date<-as.Date(as.character(Date$date), format="%m/%d/%Y")

# Creating Days
Date1<-as.data.frame(weekdays(as.Date(Date$date,'%m-%d-%Y')))
Date1<-Date1%>%dplyr::rename(date='weekdays(as.Date(Date$date, "%m-%d-%Y"))')

# Creating Months
Month<-as.data.frame(months(as.Date(Date$date,'%Y-%m-%d')))
Month<-Month%>%dplyr::rename(month=`months(as.Date(Date$date, "%Y-%m-%d"))`)

# Creating Week
Date$date<-as.Date(Date$date)
Week<-as.data.frame(stringi::stri_datetime_fields(Date$date)$WeekOfMonth)
Week<-Week%>%dplyr::rename(week="stringi::stri_datetime_fields(Date$date)$WeekOfMonth")
  
# Combining
Df<-data%>%select(Manager.Name,Reference.Name:Unsubscribed)

Df<-cbind(Df,Date1,Time, Month,Week)

Df<-Df%>%select(Manager.Name,date:week,Reference.Name:Unsubscribed)

Df$Audience.Size<-gsub(",", "", Df$Audience.Size) 
Df$Opened<-gsub(",", "", Df$Opened) 
Df$Clicked<-gsub(",", "", Df$Clicked) 

Df$Audience.Size<-as.numeric(Df$Audience.Size)
Df$Opened<-as.numeric(Df$Opened)
Df$Clicked<-as.numeric(Df$Clicked)

Df$Opened<-(Df$Opened/Df$Audience.Size)
Df$Opened<-percent(Df$Opened)

Df$Clicked<-(Df$Clicked/Df$Audience.Size)
Df$Clicked<-percent(Df$Clicked)

Df$Bounced<-(Df$Bounced/Df$Audience.Size)
Df$Bounced<-percent(Df$Bounced)

Df$Unsubscribed<-(Df$Unsubscribed/Df$Audience.Size)
Df$Unsubscribed<-percent(Df$Unsubscribed)

```


```{r}
# Data 2
#Cleaning up
Data_Time2<-strsplit(data2$Date,split = " ")
result2 <-  do.call(rbind, Data_Time2)
Date2<-as.data.frame(result2[,1])
Time2<-as.data.frame(result2[,2])

#Rename Days and Time

Date2<-Date2%>%dplyr::rename(date=`result2[, 1]`)
Time2<-Time2%>%dplyr::rename(time=`result2[, 2]`)

Date2$date<-gsub("2021","2020",Date2$date)
Time2$time<-gsub("12","00",Time2$time)

Date2$date<-as.Date(as.character(Date2$date), format="%m/%d/%Y")


# Creating Days
Date2.1<-as.data.frame(weekdays(as.Date(Date2$date,'%m-%d-%Y')))
Date2.1<-Date2.1%>%dplyr::rename(date="weekdays(as.Date(Date2$date, \"%m-%d-%Y\"))")

# Creating Months
Month2<-as.data.frame(months(as.Date(Date2$date,'%Y-%m-%d')))
Month2<-Month2%>%dplyr::rename(month=`months(as.Date(Date2$date, "%Y-%m-%d"))`)

# Creating Week
Date2$date<-as.Date(Date2$date)
Week2<-as.data.frame(stringi::stri_datetime_fields(Date2$date)$WeekOfMonth)
Week2<-Week2%>%dplyr::rename(week="stringi::stri_datetime_fields(Date2$date)$WeekOfMonth")
  
# Combining
Df2<-data2%>%select(Manager.Name,Reference.Name:Unsubscribed)

Df2<-cbind(Df2,Date2.1,Time2, Month2,Week2)

Df2<-Df2%>%select(Manager.Name,date:week,Reference.Name:Unsubscribed)

Df2$Opened<-percent(Df2$Opened)

Df2$Clicked<-percent(Df2$Clicked)

Df2$Bounced<-percent(Df2$Bounced)

Df2$Unsubscribed<-percent(Df2$Unsubscribed)

```

```{r}
# Data 3
#Cleaning up
Data_Time3<-strsplit(data3$Date,split = " ")
result3 <-  do.call(rbind, Data_Time3)
Date3<-as.data.frame(result3[,1])
Time3<-as.data.frame(result3[,2])

#Rename Days and Time

Date3<-Date3%>%dplyr::rename(date=`result3[, 1]`)
Time3<-Time3%>%dplyr::rename(time=`result3[, 2]`)

Date3$date<-gsub("2021","2020",Date3$date)

Date3$date<-as.Date(as.character(Date3$date), format="%m/%d/%Y")

# Creating Days
Date3.1<-as.data.frame(weekdays(as.Date(Date3$date,'%m-%d-%Y')))
Date3.1<-Date3.1%>%dplyr::rename(date="weekdays(as.Date(Date3$date, \"%m-%d-%Y\"))")

# Creating Months
Month3<-as.data.frame(months(as.Date(Date3$date,'%Y-%m-%d')))
Month3<-Month3%>%dplyr::rename(month=`months(as.Date(Date3$date, "%Y-%m-%d"))`)

# Creating Week
Date3$date<-as.Date(Date3$date)
Week3<-as.data.frame(stringi::stri_datetime_fields(Date3$date)$WeekOfMonth)
Week3<-Week3%>%dplyr::rename(week="stringi::stri_datetime_fields(Date3$date)$WeekOfMonth")
  
# Combining
Df3<-data3%>%select(Manager.Name,Reference.Name:Unsubscribed)

Df3<-cbind(Df3,Date3.1,Time3, Month3,Week3)

Df3<-Df3%>%select(Manager.Name,date:week,Reference.Name:Unsubscribed)
```

```{r}
# Data 4
#Cleaning up
Data_Time4<-strsplit(data4$Date,split = " ")
result4 <-  do.call(rbind, Data_Time4)
Date4<-as.data.frame(result4[,1])
Time4<-as.data.frame(result4[,2])

#Rename Days and Time

Date4<-Date4%>%dplyr::rename(date=`result4[, 1]`)
Time4<-Time4%>%dplyr::rename(time=`result4[, 2]`)

Date4$date<-gsub("2021","2020",Date4$date)

Date4$date<-as.Date(as.character(Date4$date), format="%m/%d/%Y")

# Creating Days
Date4.1<-as.data.frame(weekdays(as.Date(Date4$date,'%m-%d-%Y')))
Date4.1<-Date4.1%>%dplyr::rename(date="weekdays(as.Date(Date4$date, \"%m-%d-%Y\"))")

# Creating Months
Month4<-as.data.frame(months(as.Date(Date4$date,'%Y-%m-%d')))
Month4<-Month4%>%dplyr::rename(month=`months(as.Date(Date4$date, "%Y-%m-%d"))`)

# Creating Week
Date4$date<-as.Date(Date4$date)
Week4<-as.data.frame(stringi::stri_datetime_fields(Date4$date)$WeekOfMonth)
Week4<-Week4%>%dplyr::rename(week="stringi::stri_datetime_fields(Date4$date)$WeekOfMonth")
  
# Combining
Df4<-data4%>%select(Manager.Name,Reference.Name:Unsubscribed)

Df4<-cbind(Df4,Date4.1,Time4, Month4,Week4)

Df4<-Df4%>%select(Manager.Name,date:week,Reference.Name:Unsubscribed)
```

```{r}
Complete_data<-rbind(Df,Df2)
Complete_data<-rbind(Complete_data,Df3)
Complete_data<-rbind(Complete_data,Df4)

Complete_data2<-Complete_data[-c(132),]

Complete_data2$Audience.Size<-gsub(",", "", Complete_data2$Audience.Size) 
Complete_data2$Audience.Size<-as.numeric(Complete_data2$Audience.Size)

Complete_data2$Opened<-gsub("%","",Complete_data2$Opened)
Complete_data2$Clicked<-gsub("%","",Complete_data2$Clicked)
Complete_data2$Bounced<-gsub("%","",Complete_data2$Bounced)
Complete_data2$Unsubscribed<-gsub("%","",Complete_data2$Unsubscribed)

Complete_data2$Opened<-round(as.numeric(Complete_data2$Opened),2)
Complete_data2$Clicked<-round(as.numeric(Complete_data2$Clicked),2)
Complete_data2$Bounced<-round(as.numeric(Complete_data2$Bounced),2)
Complete_data2$Unsubscribed<-round(as.numeric(Complete_data2$Unsubscribed),2)
```




```{r}
# Basic Desciptives
psych::describe(Complete_data2)
```


```{r,echo=FALSE}
#Frequency
freq(Complete_data2$Manager.Name)
freq(Complete_data2$From)
freq(Complete_data2$Mail.Type)
freq(Complete_data2$Product.Name)
freq(Complete_data2$Subscription)
freq(Complete_data2$Blast.Message)
freq(Complete_data2$Distribution.Partner.Specific)
freq(Complete_data2$Preferred.Partner)
freq(Complete_data2$Producers.Only)
freq(Complete_data2$Prospects.Only)
```

```{r}
#Outliers
Out.Audience.Size<-boxplot.stats(Complete_data2$Audience.Size)$out
Out.Open.Rate<-boxplot.stats(Complete_data2$Opened)$out
Out.Clickthrough.Rate<-boxplot.stats(Complete_data2$Clicked)$out
Out.Bounce.Rate<-boxplot.stats(Complete_data2$Bounced)$out
Out.Unsubscibe.Rate<-boxplot.stats(Complete_data2$Unsubscribed)$out

#Boxplot
ggplot(Complete_data2) +
  aes(x="",y=Audience.Size)+
  geom_boxplot(fill="#0c4c8a")+
  theme_minimal()
  
ggplot(Complete_data2) +
  aes(x = "", y = Opened) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = "", y = Clicked) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = "", y =Bounced) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = "", y = Unsubscribed) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

# Histograms


ggplot(Complete_data2) +
  aes(x = Audience.Size) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = Opened) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = Clicked) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = Bounced) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data2) +
  aes(x = Unsubscribed) +
  geom_histogram(bins = 30L, fill = "#0c4c8a") +
  theme_minimal()
```

```{r}
# QQplot
#Audience Size needs to be fixed
qq.Audience.Size <- qqPlot(Complete_data2$Audience.Size)
qq.Open.Rate<-qqPlot(Complete_data2$Opened)
qq.Clickthrough.Rate<-qqPlot(Complete_data2$Clicked)
qq.Bounce.Rate<-qqPlot(Complete_data2$Bounced)
qq.Unsubscribe.Rate<-qqPlot(Complete_data2$Unsubscribed)

# Density Plot
ggdensity(Complete_data2$Audience.Size,
          main= "Density plot of Open Rate",
          xlab = "Audience size")

ggdensity(Complete_data2$Opened,
          main= "Density plot of Open Rate",
          xlab= "Open Rate")

ggdensity(Complete_data2$Clicked,
          main= "Density plot of Clickthrough Rate",
          xlab= "Clickthrough Rate")

ggdensity(Complete_data2$Bounced,
          main= "Density plot of Bounce Rate",
          xlab= "Bounce Rate")

ggdensity(Complete_data2$Unsubscribed,
          main= "Density plot of Unsubscribe Rate",
          xlab= "Unsubscribe Rate")

##Shapiro-Test Wilks
shapiro.test(Complete_data2$Audience.Size)
shapiro.test(Complete_data2$Opened)
shapiro.test(Complete_data2$Clicked)
shapiro.test(Complete_data2$Bounced)
shapiro.test(Complete_data2$Unsubscribed)

#Skewness
skewness(Complete_data2$Audience.Size,na.rm = TRUE)
skewness(Complete_data2$Opened,na.rm = TRUE)
skewness(Complete_data2$Clicked,na.rm = TRUE)
skewness(Complete_data2$Bounced,na.rm = TRUE)
skewness(Complete_data2$Unsubscribed,na.rm = TRUE)

#kurtosis
kurtosis(Complete_data2$Audience.Size,na.rm = TRUE)
kurtosis(Complete_data2$Opened,na.rm = TRUE)
kurtosis(Complete_data2$Clicked,na.rm = TRUE)
kurtosis(Complete_data2$Bounced,na.rm = TRUE)
kurtosis(Complete_data2$Unsubscribed,na.rm = TRUE)

```


```{r}
#Quantile
quantile(Complete_data2$Audience.Size, na.rm=TRUE)
quantile(Complete_data2$Opened,na.rm = TRUE)
quantile(Complete_data2$Clicked,na.rm = TRUE)
quantile(Complete_data2$Bounced,na.rm=TRUE)
quantile(Complete_data2$Unsubscribed,na.rm=TRUE)

```


```{r}
#Contigency Tables: mean of DVs at each level of each categorical IV
#From.Firm
Complete_data2%>%group_by(From)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

#email Type
Complete_data2%>%group_by(Mail.Type)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

#Product Name
Complete_data2%>%group_by(Product.Name)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

#Subscription
Complete_data2%>%group_by(Subscription)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

# Blast Message
Complete_data2%>%group_by(Blast.Message)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

# Distribution Partner Specific
Complete_data2%>%group_by(Distribution.Partner.Specific)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

# Preferred Partner
Complete_data2%>%group_by(Preferred.Partner)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

# Producers Only 
Complete_data2%>%group_by(Producers.Only)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

# Prospects 
Complete_data2%>%group_by(Prospects.Only)%>%
  dplyr::summarise(open_mean = mean(Opened),
            clickthrough_mean = mean(Clicked),
            bounce_mean = mean(Bounced),
            unsubscribe_mean = mean(Unsubscribed),
            n())

```


```{r}
# Data visualization
ggplot(Complete_data2, aes(time, date, fill = Opened)) +
  geom_tile(colour = "blue") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Open Rate",
       fill="Close")
#Plot 2
ggplot(Complete_data2, aes(time, date, fill = Clicked)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Clickthrough Rate",
       fill="Close")

#Plot 3
ggplot(Complete_data2, aes(time, date, fill = Bounced)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Bounce Rate",
       fill="Close")

#Plot 4
ggplot(Complete_data2, aes(time, date, fill = Unsubscribed)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Unsubscribe Rate",
       fill="Close")

```

```{r}
# Regression and Machine Learning
validation_index <- createDataPartition(Complete_data_SD_2$Opened, p=0.80, list=FALSE)

validation <- Complete_data_SD_2[-validation_index,]

dataset <- Complete_data_SD_2[validation_index,]

control <- trainControl(method = "cv", 
                              number = 5,verboseIter = TRUE)
metric="RMSE"

################ Open Rate
set.seed(7)
model.knn <- train(Opened~Manager.Name + From + Mail.Type + Subscription + Blast.Message + 
                     Distribution.Partner.Specific + Preferred.Partner
                   + Producers.Only + Prospects.Only, data=dataset, method="knn", metric=metric, trControl=control)

set.seed(9)
model.lm <- train(Open.Rate ~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                  + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                  + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                  + US.AUM + US.Intermediary.AUM, data = dataset, method = "lm", metric=metric,
                  trControl = control)
summary(model.lm)

predictions <- predict(model.lm, validation)
prediction<-as.data.frame(cbind(predictions,validation$Open.Rate))

################ Clickthrought
set.seed(7)
model.knn <- train(Clickthrought.Rate~ Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                   + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                   + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                   + US.AUM + US.Intermediary.AUM, data=dataset, method="knn", metric=metric, trControl=control)

set.seed(9)
model.lm <- train(Clickthrought.Rate ~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                  + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                  + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                  + US.AUM + US.Intermediary.AUM, data = dataset, method = "lm", metric=metric,
                  trControl = train.control)
summary(model.lm)

predictions <- predict(model.lm, validation)
confusionMatrix(predictions, validation$Clickthrought.Rate)

################ Bounce Rate
set.seed(7)
model.knn <- train(Bounce.Rate~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                   + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                   + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                   + US.AUM + US.Intermediary.AUM, data=dataset, method="knn", metric=metric, trControl=control)

set.seed(9)
model.lm <- train(Bounce.Rate ~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                  + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                  + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                  + US.AUM + US.Intermediary.AUM, data = dataset, method = "lm", metric=metric,
                  trControl = train.control)
summary(model.lm)

predictions <- predict(model.lm, validation)
confusionMatrix(predictions, validation$Bounce.Rate)

################ Unsubscribe
set.seed(7)
model.knn <- train(Unsubscribe.Rate~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                   + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                   + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                   + US.AUM + US.Intermediary.AUM, data=dataset, method="knn", metric=metric, trControl=control)

set.seed(9)
model.lm <- train(Unsubscribe.Rate ~Reference.Name + From.Firm + email.Type + Product.Name + Subscription
                  + Audience.Size + Blast.Message + Distribution.Partner.Specific + Preferred.Partner
                  + Producers.Only + Prospect.Only + AUM + Morningstar.Rating + Focus.Status 
                  + US.AUM + US.Intermediary.AUM, data = dataset, method = "lm", metric=metric,
                  trControl = train.control)
summary(model.lm)

predictions <- predict(model.lm, validation)
confusionMatrix(predictions, validation$Unsubscribe.Rate)
```

```{r}
regression_model<-lm(Opened~date+month+Reference.Name+From+Mail.Type+Product.Name+Subscription+Blast.Message+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only,data=Complete_data)

summary(regression_model)

## Changing to factors
Complete_data_factors<-Complete_data

mean(Complete_data[,17],na.rm = TRUE)
mean(Complete_data[,18],na.rm = TRUE)
mean(Complete_data[,19],na.rm = TRUE)
mean(Complete_data[,20],na.rm = TRUE)

Complete_data_factors$Opened[Complete_data$Opened < 17] <- 0
Complete_data_factors$Opened[Complete_data$Opened > 17] <- 1 

Complete_data_factors$Clicked[Complete_data$Clicked < 6.5] <- 0
Complete_data_factors$Clicked[Complete_data$Clicked > 6.5] <- 1

Complete_data_factors$Bounced[Complete_data$Bounced < 1.3] <- 0
Complete_data_factors$Bounced[Complete_data$Bounced > 1.3] <- 1

Complete_data_factors$Unsubscribed[Complete_data < 0.01] <- 0
Complete_data_factors$Unsubscribed[Complete_data > 0.01] <- 1

Complete_data_factors$Opened<-as.factor(Complete_data_factors$Opened)


Complete_data_factors<-Complete_data%>% mutate(From=recode_factor(From,
                                               "TRUE"='1',
                                               "FALSE"='0'))




Complete_data_factors$Subscription<-as.factor(Complete_data_factors$Subscription)
Complete_data_factors$Distribution.Partner.Specific<-as.factor(Complete_data_factors$Distribution.Partner.Specific)
Complete_data_factors$Preferred.Partner<-as.factor(Complete_data_factors$Preferred.Partner)
Complete_data_factors$Producers.Only<-as.factor(Complete_data_factors$Producers.Only)
Complete_data_factors$Prospects.Only<-as.factor(Complete_data_factors$Prospects.Only)



dt = sort(sample(nrow(Complete_data_factors), nrow(Complete_data_factors)*.7))
train<-Complete_data_factors[dt,]
test<-Complete_data_factors[-dt,]

k_fold<-vfold_cv(train)

model_rec<-recipe(Opened~From+Subscription+Blast.Message+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only, train) %>%
  step_range(all_numeric())

m_metrics<-metric_set(accuracy, sens, spec, roc_auc, mn_log_loss)

m_control<-control_grid(save_pred =TRUE)

model2<-nearest_neighbor(neighbors =tune("K")) %>%
  set_mode("classification") %>%
  set_engine("kknn")

set.seed(123)
knn_tune<-tune_grid(model2,
                    model_rec,resamples = k_fold,
                    control=m_control,
                    metrics = m_metrics)



```


```{r}
Complete_data_SD<-Complete_data2

Complete_data_SD$From<-gsub("TRUE","1",Complete_data_SD$From)
Complete_data_SD$From<-gsub("FALSE","0",Complete_data_SD$From)

Complete_data_SD$Subscription<-gsub("TRUE","1",Complete_data_SD$Subscription)
Complete_data_SD$Subscription<-gsub("FALSE","0",Complete_data_SD$Subscription)

Complete_data_SD$Blast.Message<-gsub("TRUE","1",Complete_data_SD$Blast.Message)
Complete_data_SD$Blast.Message<-gsub("FALSE","0",Complete_data_SD$Blast.Message)

Complete_data_SD$Distribution.Partner.Specific<-gsub("TRUE","1",Complete_data_SD$Distribution.Partner.Specific)
Complete_data_SD$Distribution.Partner.Specific<-gsub("FALSE","0",Complete_data_SD$Distribution.Partner.Specific)

Complete_data_SD$Preferred.Partner<-gsub("TRUE","1",Complete_data_SD$Preferred.Partner)
Complete_data_SD$Preferred.Partner<-gsub("FALSE","0",Complete_data_SD$Preferred.Partner)

Complete_data_SD$Producers.Only<-gsub("TRUE","1",Complete_data_SD$Producers.Only)
Complete_data_SD$Producers.Only<-gsub("FALSE","0",Complete_data_SD$Producers.Only)

Complete_data_SD$Prospects.Only<-gsub("TRUE","1",Complete_data_SD$Prospects.Only)
Complete_data_SD$Prospects.Only<-gsub("FALSE","0",Complete_data_SD$Prospects.Only)

Complete_data_SD$Mail.Type<-as.factor(Complete_data_SD$Mail.Type)
Complete_data_SD$From<-as.factor(Complete_data_SD$From)
Complete_data_SD$Subscription<-as.factor(Complete_data_SD$Subscription)
Complete_data_SD$Distribution.Partner.Specific<-as.factor(Complete_data_SD$Distribution.Partner.Specific)
Complete_data_SD$Preferred.Partner<-as.factor(Complete_data_SD$Preferred.Partner)
Complete_data_SD$Producers.Only<-as.factor(Complete_data_SD$Producers.Only)
Complete_data_SD$Prospects.Only<-as.factor(Complete_data_SD$Prospects.Only)

Complete_data_SD_2<-Complete_data_SD%>%
  select(Manager.Name,From:Mail.Type,Subscription:Unsubscribed)

Complete_data_SD_2$Opened<-scale(Complete_data_SD_2$Opened,center = TRUE,scale = TRUE)
Complete_data_SD_2$Opened[Complete_data_SD_2$Opened < 0] <- 0
Complete_data_SD_2$Opened[Complete_data_SD_2$Opened > 0] <- 1 
Complete_data_SD_2$Opened<-as.factor(Complete_data_SD_2$Opened)


df_split<-initial_split(Complete_data_SD_2,prop=.7,strata = Opened)
df.train<-training(df_split)
df.test<-testing(df_split)

k_fold<-vfold_cv(df.train)

model_rec<-recipe(Opened~From+Subscription+Blast.Message+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only, df.train) %>%
  step_range(all_numeric())

m_metrics<-metric_set(accuracy, sens, spec, roc_auc, mn_log_loss)
m_control<-control_grid(save_pred =TRUE)

model2<-nearest_neighbor(neighbors =tune("K"))%>%
  set_mode("classification")%>%
  set_engine("kknn")

set.seed(123)
knn_tune<-tune_grid(model2,  
                    model_rec,
                    resamples = k_fold,
                    control=m_control,
                    metrics = m_metrics)

```

