---
title: "Summary Table"
author: "Eagle IO"
date: "1/26/2021"
output: html_document
---



```{r, include=FALSE}
#Descriptive Table
table1::label(Complete_data4$Asset.Manager.AUM.Dollars.Million) <- "Asset Manager AUM ($M)"
table1::label(Complete_data4$Asset.Manager.Inter.AUM.Dollars.Million) <- "Asset Manager Intermediary AUM ($M)"
table1::label(Complete_data4$AUM.Dollars.Million) <- "AUM ($M)"
table1::label(Complete_data4$Mail.Type) <- "Mail Type"
table1::label(Complete_data4$Audience.Size) <- "Audience Size"
table1::label(Complete_data4$Opened) <- "Opened"
table1::label(Complete_data4$Clicked) <- "Clicked"
table1::label(Complete_data4$Bounced) <- "Bounced"
table1::label(Complete_data4$Unsubscribed) <- "Unsubscribed"

table1::table1(~Asset.Manager.AUM.Dollars.Million+Asset.Manager.Inter.AUM.Dollars.Million+AUM.Dollars.Million+Mail.Type+  Audience.Size+Opened+Clicked+Bounced+Unsubscribed | Manager.Name.x, data=Complete_data4)

```


```{r,include=FALSE}
# Frequency Table
lst2 <- lapply(Complete_data4, function(x) {
  out <- as.data.frame.table(table(x))
  out$Pct <- 100*out$Freq/sum(out$Freq)
  out
})

Freq1<-do.call(rbind, c(Map(cbind, nm=names(lst2), lst2), list(make.row.names = FALSE)))

```


```{r, include=FALSE}
# Testing for Normality
## Box plots

ggplot(Complete_data4) +
  aes(x="",y=Audience.Size)+
  geom_boxplot(fill="#0c4c8a")+
  theme_minimal()
  
ggplot(Complete_data4) +
  aes(x = "", y = Opened) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data4) +
  aes(x = "", y = Clicked) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data4) +
  aes(x = "", y =Bounced) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

ggplot(Complete_data4) +
  aes(x = "", y = Unsubscribed) +
  geom_boxplot(fill = "#0c4c8a") +
  theme_minimal()

#Outliers
Out.Audience.Size<-boxplot.stats(Complete_data4$Audience.Size)$out
Out.Open.Rate<-boxplot.stats(Complete_data4$Opened)$out
Out.Clickthrough.Rate<-boxplot.stats(Complete_data4$Clicked)$out
Out.Bounce.Rate<-boxplot.stats(Complete_data4$Bounced)$out
Out.Unsubscibe.Rate<-boxplot.stats(Complete_data4$Unsubscribed)$out

```

```{r, include=FALSE}
#Qqplot

qq.Audience.Size <- qqPlot(Complete_data4$Audience.Size)
qq.Open.Rate<-qqPlot(Complete_data4$Opened)
qq.Clickthrough.Rate<-qqPlot(Complete_data4$Clicked)
qq.Bounce.Rate<-qqPlot(Complete_data4$Bounced)
qq.Unsubscribe.Rate<-qqPlot(Complete_data4$Unsubscribed)

ggdensity(Complete_data4$Audience.Size,
          main= "Density plot of Audience Size",
          xlab = "Audience size")

ggdensity(Complete_data4$Opened,
          main= "Density plot of Open Rate",
          xlab= "Open Rate")

ggdensity(Complete_data4$Clicked,
          main= "Density plot of Clickthrough Rate",
          xlab= "Clickthrough Rate")

ggdensity(Complete_data4$Bounced,
          main= "Density plot of Bounce Rate",
          xlab= "Bounce Rate")

ggdensity(Complete_data4$Unsubscribed,
          main= "Density plot of Unsubscribe Rate",
          xlab= "Unsubscribe Rate")


```







```{r,include=FALSE}
# heatmaps


ggplot(Complete_data4, aes(time_of_Day, date, fill = Opened)) +
  geom_tile(colour = "blue") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Open Rate",
       fill="Close")


ggplot(Complete_data4, aes(time, date, fill = Clicked)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Clickthrough Rate",
       fill="Close")

#Plot 3
ggplot(Complete_data4, aes(time, date, fill = Bounced)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Bounce Rate",
       fill="Close")

#Plot 4
ggplot(Complete_data4, aes(time, date, fill = Unsubscribed)) +
  geom_tile(colour = "white") +
  facet_grid(week~month) +
  scale_fill_gradient(low="red", high="green") +
  labs(x="Time of Day",
       y="",
       title = "Time-Series Calendar Heatmap",
       subtitle="Email Unsubscribe Rate",
       fill="Close")


```






```{r,include=FALSE}
# Prediction
Regression_Data<-Complete_data4%>%select(Manager.Name.x,Headquarter.City,Scope.of.AUM:Asset.Manager.Inter.AUM.Dollars.Million,Reference.Name,From,Mail.Type,Subscription:Prospects.Only,date,month,week,Opened:Unsubscribed)

# turning into factors
Regression_Data$From<-gsub("TRUE","1",Regression_Data$From)
Regression_Data$From<-gsub("FALSE","0",Regression_Data$From)

Regression_Data$Subscription<-gsub("TRUE","1",Regression_Data$Subscription)
Regression_Data$Subscription<-gsub("FALSE","0",Regression_Data$Subscription)

Regression_Data$Blast.Message<-gsub("TRUE","1",Regression_Data$Blast.Message)
Regression_Data$Blast.Message<-gsub("FALSE","0",Regression_Data$Blast.Message)

Regression_Data$Distribution.Partner.Specific<-gsub("TRUE","1",Regression_Data$Distribution.Partner.Specific)
Regression_Data$Distribution.Partner.Specific<-gsub("FALSE","0",Regression_Data$Distribution.Partner.Specific)

Regression_Data$Preferred.Partner<-gsub("TRUE","1",Regression_Data$Preferred.Partner)
Regression_Data$Preferred.Partner<-gsub("FALSE","0",Regression_Data$Preferred.Partner)

Regression_Data$Producers.Only<-gsub("TRUE","1",Regression_Data$Producers.Only)
Regression_Data$Producers.Only<-gsub("FALSE","0",Regression_Data$Producers.Only)

Regression_Data$Prospects.Only<-gsub("TRUE","1",Regression_Data$Prospects.Only)
Regression_Data$Prospects.Only<-gsub("FALSE","0",Regression_Data$Prospects.Only)

Regression_Data$Mail.Type<-gsub("/Hybrid","",Regression_Data$Mail.Type)
Regression_Data$Mail.Type<-gsub(" / Hybrid","",Regression_Data$Mail.Type)
Regression_Data$Mail.Type<-gsub("Unknown","Other",Regression_Data$Mail.Type)



Regression_Data$Manager.Name.x<-as.factor(Regression_Data$Manager.Name.x)
Regression_Data$Headquarter.City<-as.factor(Regression_Data$Headquarter.City)
Regression_Data$Scope.of.AUM<-as.factor(Regression_Data$Scope.of.AUM)
Regression_Data$Scope.of.Intermediary.AUM<-as.factor(Regression_Data$Scope.of.Intermediary.AUM)
Regression_Data$Reference.Name<-as.factor(Regression_Data$Reference.Name)
Regression_Data$Mail.Type<-as.factor(Regression_Data$Mail.Type)
Regression_Data$From<-as.factor(Regression_Data$From)
Regression_Data$Subscription<-as.factor(Regression_Data$Subscription)
Regression_Data$Blast.Message<-as.factor(Regression_Data$Blast.Message)
Regression_Data$Distribution.Partner.Specific<-as.factor(Regression_Data$Distribution.Partner.Specific)
Regression_Data$Preferred.Partner<-as.factor(Regression_Data$Preferred.Partner)
Regression_Data$Producers.Only<-as.factor(Regression_Data$Producers.Only)
Regression_Data$Prospects.Only<-as.factor(Regression_Data$Prospects.Only)
Regression_Data$date<-as.factor(Regression_Data$date)
Regression_Data$month<-as.factor(Regression_Data$month)
Regression_Data$week<-as.factor(Regression_Data$week)


# Z Score Opened Ratings
Regression_Data$Opened<-scale(Regression_Data$Opened,center = TRUE,scale = TRUE)
Regression_Data$Opened[Regression_Data$Opened < 0] <- 0
Regression_Data$Opened[Regression_Data$Opened > 0] <- 1 
Regression_Data$Opened<-as.factor(Regression_Data$Opened)

#KNN
df_split<-initial_split(Regression_Data,prop=.8,strata = Opened)
df.train<-training(df_split)
df.test<-testing(df_split)

k_fold<-vfold_cv(df.train)

model_rec<-recipe(Opened~Manager.Name.x+Headquarter.City+Scope.of.Intermediary.AUM+Scope.of.AUM+From+Mail.Type+Subscription+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only,date,month, df.train) %>%
  step_range(all_numeric())


m_metrics<-metric_set(accuracy, sens, spec, roc_auc, mn_log_loss)
m_control<-control_grid(save_pred =TRUE)

model2<-nearest_neighbor(neighbors =tune("K"))%>%
  set_mode("classification")%>%
  set_engine("kknn")

set.seed(123)
knn_tune<-tune_grid(model2,  
                    model_rec,
                    resamples = k_fold,
                    control=m_control,
                    metrics = m_metrics)

knn_tune %>%collect_metrics() %>%
  ggplot(aes(x=K, y=mean))+
  geom_point()+
  geom_line()+
  facet_wrap(~.metric, scales ="free_y")

```


```{r}
# Random Forest
library(caTools)
set.seed(123)

split<-sample.split(Regression_Data$Opened, SplitRatio =0.7)
train<-subset(Regression_Data, split==TRUE)
test<-subset(Regression_Data, split==FALSE)


dtree1<-rpart(Opened~Manager.Name.x+Headquarter.City+Scope.of.Intermediary.AUM+Scope.of.AUM+From+Mail.Type+Subscription+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only, data = train, 
              method="class",
              minsplit=2, 
              minbucket=1,
              cp=0.005)

summary(dtree1)
rpart.plot(dtree1)

test.pred<-predict(dtree1, test, type ="class")
confusionMatrix(test.pred, test$Opened)


set.seed(234)
system.time(
  rf1<-randomForest(Opened~Manager.Name.x+Headquarter.City+Scope.of.Intermediary.AUM+Scope.of.AUM+From+Mail.Type+Subscription+Distribution.Partner.Specific+Preferred.Partner+Producers.Only+Prospects.Only, data=train, mtry=2, ntree=501)
            )

test.predtr<-predict(rf1, train, type ="class")
confusionMatrix(test.predtr, train$Opened)

test.predts<-predict(rf1, test, type ="class")
confusionMatrix(test.predts, test$Opened)

```



```{r}
Headcount<-Complete_data4%>%select(Manager.Name.x,Mail.Type,Product.Name,Audience.Size,Opened:Unsubscribed)


Open_Rate<-Complete_data4%>%select(Manager.Name.x,Opened)
Click_Rate<-Complete_data4%>%select(Manager.Name.x,Clicked)
Bounce_Rate<-Complete_data4%>%select(Manager.Name.x,Bounced)
Unsubscribe_Rate<-Complete_data4%>%select(Manager.Name.x,Unsubscribed)

Open_Rate$Subscribers<-"Open"
Click_Rate$Subscribers<-"Clicked"
Bounce_Rate$Subscribers<-"Bounced"
Unsubscribe_Rate$Subscribers<-"Unsubscribed"

Open_Rate<-Open_Rate%>%dplyr::rename(Percent=Opened)
Click_Rate<-Click_Rate%>%dplyr::rename(Percent=Clicked)
Bounce_Rate<-Bounce_Rate%>%dplyr::rename(Percent=Bounced)
Unsubscribe_Rate<-Unsubscribe_Rate%>%dplyr::rename(Percent=Unsubscribed)

Rates<-rbind(Open_Rate,Click_Rate)
Rates<-rbind(Rates,Bounce_Rate)
Rates<-rbind(Rates,Unsubscribe_Rate)

Rates$Percent<-Rates$Percent*formattable::percent(.01)

ggplot(Rates) +
 aes(x = Manager.Name.x, fill = Subscribers, weight = Percent) +
 geom_bar() +
 scale_fill_hue() +
 labs(x = "Company", y = "Percent (%)", title = "Rates by Company") +
 coord_flip() +
 theme_minimal()

ggplot(Rates) +
 aes(x = Manager.Name.x, fill = Subscribers, weight = Percent) +
 geom_bar(position = "dodge") +
 scale_fill_hue() +
 labs(x = "Company", y = "Percent", title = "Rates by Company") +
 coord_flip() +
 theme_minimal()

ggplot(data6) +
 aes(x = Morningstar.Rating, y = Product.Name, fill = Manager.Name) +
 geom_tile(size = 1L) +
 scale_fill_hue() +
 theme_minimal()

esquisser(Rates)


           
                            


```




